spring:
  datasource:
    # 配置自带数据库的相对路径
    url: jdbc:h2:~/.datasophon/db/datasophon_dev;MODE=MYSQL
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true