#!/bin/sh
#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# chkconfig: 35 95 1
usage="Usage: start.sh (start|stop|restart) <command> "

startStop=$1
installPath=$2

case $startStop in
  (start)
    sh /opt/datasophon/datasophon-worker/bin/datasophon-worker.sh start worker
    ;;
  (stop)
    sh /opt/datasophon/datasophon-worker/bin/datasophon-worker.sh stop worker
      ;;
  (status)
    sh /opt/datasophon/datasophon-worker/bin/datasophon-worker.sh status worker
      ;;
  (restart)
    sh /opt/datasophon/datasophon-worker/bin/datasophon-worker.sh restart worker
      ;;
  (*)
    echo $usage
    exit 1
    ;;

esac

echo "End $startStop $command."